#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Assertions for tools/csv-to-board.py. Chore C20.

    python3 tools/test-csv-to-board.py

Prints a count, because an exit code cannot show a suite that stopped running.

Each assertion here exists to catch a NAMED mutation (M29-M33 in the register), and each
mutation was applied to the shipped code and seen to fail before its row was written. The
project has five recorded cases of an assertion that read correctly, passed, and could not
detect the behaviour it named. Two habits from those, kept deliberately here:

  * assertions read the tool's real OUTPUT — the generated bytes, the process exit code —
    rather than re-deriving what the answer ought to be. An assertion that recomputes its
    expectation cannot see the path that produces the real one;
  * the manifest assertion builds a manifest FROM the generated entry and validates THAT
    (`M28`), instead of trusting the model the entry came from.
"""

import json
import os
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOL = os.path.join(REPO, 'tools', 'csv-to-board.py')
MAP = os.path.join(REPO, 'examples', 'revenue-feud.map.json')
CSV = os.path.join(REPO, 'examples', 'revenue_responses_17.csv')

PASSED = []
FAILED = []


def check(name, condition, detail=''):
    (PASSED if condition else FAILED).append(name)
    if not condition:
        print(f'  FAIL  {name}' + (f'\n        {detail}' if detail else ''))


def run(map_path=MAP, csv_path=CSV, extra=()):
    """Run the generator as a SUBPROCESS — the way a user runs it, exit code and all."""
    return subprocess.run(
        [sys.executable, TOOL, map_path, '--csv', csv_path, *extra],
        capture_output=True, text=True, cwd=REPO)


def generate(tmp, map_path=MAP, csv_path=CSV):
    """Generate into a scratch directory and read back the FILES, not the objects."""
    games = os.path.join(tmp, 'games')
    os.makedirs(games, exist_ok=True)
    manifest = os.path.join(games, 'games.json')
    with open(os.path.join(REPO, 'games', 'games.json'), encoding='utf-8') as fh:
        seed = fh.read()
    open(manifest, 'w', encoding='utf-8').write(seed)
    proc = run(map_path, csv_path, ('--games-dir', games, '--manifest', manifest, '--write'))
    return proc, games, manifest


def load(path):
    with open(path, encoding='utf-8') as fh:
        return json.load(fh)


def validate(kind, path):
    return subprocess.run(
        ['node', os.path.join(REPO, 'tools', 'validate-board.mjs'), kind, path],
        capture_output=True, text=True, cwd=REPO)


# ---------------------------------------------------------------------------

def test_happy_path(tmp):
    proc, games, manifest = generate(tmp)
    check('the generator exits 0 on the shipped map and CSV', proc.returncode == 0, proc.stderr)
    board_path = os.path.join(games, 'revenue-feud.json')
    check('it writes the board file named by the map', os.path.exists(board_path))
    if not os.path.exists(board_path):
        return None, None
    return load(board_path), manifest


def test_columns_total_100(board):
    """M30 — largest remainder. A column that DROPS answers is the one that matters:
    plain flooring leaves it short, and plain rounding cannot reach 100 at all."""
    if not board:
        return
    totals = {c['label']: sum(x['value'] for x in c['cells']) for c in board['board']['columns']}
    bad = {k: v for k, v in totals.items() if v != 100}
    check('every column\'s point values sum to exactly 100', not bad, f'off: {bad}')

    dropping = 'What is Illinois\' primary source of revenue?'
    col = next((c for c in board['board']['columns'] if c['label'] == dropping), None)
    check('a column with a DROPPED answer still sums to 100',
          col is not None and sum(x['value'] for x in col['cells']) == 100,
          'this column drops "Investments"; its share must redistribute, not vanish')


def test_apportionment_basis(board):
    """M33b — the policing column has one blank and one dropped answer among 17 responses.

    A fixture chosen because the two implementations DISAGREE on it. 7 of 17 is 41.2 and
    7 of the 16 who answered is 43.8; after apportionment over the 15 kept responses the
    right answer is 47 and the blank-excluding one is 47 too — so the raw share is
    asserted instead, where they differ. A fixture both implementations satisfy
    distinguishes nothing.
    """
    if not board:
        return
    col = next((c for c in board['board']['columns']
                if c['label'].startswith('How much of the Illinois budget')), None)
    if col is None:
        check('the policing column is present', False)
        return
    # 17 rows: 7x"10%", 6x"5%", 1x"3%", 1x"4", 1x"Too damn much" (dropped), 1 blank.
    # Kept = 7 + 6 + 2 = 15. Ten of 15 is not a thing any total-responses reading gives.
    ten = next(x['value'] for x in col['cells'] if x['answer'] == '10%')
    check('the policing column apportions over KEPT responses, blanks excluded from the share',
          ten == 47, f'"10%" came out at {ten}, expected 47 (7 of 15 kept)')


def test_dropped_answers_do_not_reach_the_board(board):
    """M33 — `drop` is the editorial half of the map and nothing enforces it but this.

    Asserted as the whole SET per column, not as "Investments is absent": a mutation that
    leaks the drop list leaks every entry of it, and a membership test on one name would
    pass for the other seven columns while the board filled up with long tail.
    """
    if not board:
        return
    m = load(MAP)
    for col_map, col in zip(m['columns'], board['board']['columns']):
        expected = [a['label'] for a in col_map['answers']]
        actual = [c['answer'] for c in col['cells']]
        check(f'{col["label"][:40]!r}: the board carries exactly the map\'s answers, in order',
              actual == expected, f'expected {expected}, got {actual}')


def test_unmapped_answer_is_an_error(tmp):
    """M29 — the gate that makes this tool safe to re-run on a grown survey."""
    m = load(MAP)
    # Remove ONE alias. The response is still in the CSV, so it is now unmapped.
    for col in m['columns']:
        if col['csvColumn'] == 'Which CTA bus line needs the most investment?':
            col['answers'] = [a for a in col['answers'] if a['label'] != '49']
    broken = os.path.join(tmp, 'unmapped.map.json')
    open(broken, 'w', encoding='utf-8').write(json.dumps(m))
    proc = run(broken)
    check('an answer in neither "from" nor "drop" fails the run',
          proc.returncode != 0, f'exit was {proc.returncode}')
    check('and the failure names the offending answer',
          '49 the spine' in proc.stderr, proc.stderr.strip()[:200])


def test_renamed_csv_column_is_an_error(tmp):
    """A survey question renamed between exports must not silently produce a short board."""
    rows = open(CSV, encoding='utf-8').read().replace(
        'Which CTA bus line needs the most investment?',
        'Which CTA bus route needs the most investment?', 1)
    moved = os.path.join(tmp, 'renamed.csv')
    open(moved, 'w', encoding='utf-8').write(rows)
    proc = run(MAP, moved)
    check('a renamed CSV column fails the run rather than dropping a board column',
          proc.returncode != 0, f'exit was {proc.returncode}')


def test_manifest_entry_is_a_valid_manifest(tmp, manifest_path):
    """M31 — the entry is asserted AS A MANIFEST, by the thing that consumes manifests.

    This is `M28` in a new tool. The editor once emitted a games.json line built from the
    wrong field and never escaped; the assertion that caught it built a manifest from the
    line and validated that, rather than inspecting the model it came from.
    """
    if not manifest_path:
        return
    r = validate('games', manifest_path)
    check('the generated games.json is a valid manifest, per the engine',
          r.returncode == 0, r.stderr.strip()[:300])

    m = load(MAP)

    # The shipped map sets title == pickerKey, so it CANNOT distinguish an implementation
    # that keys the manifest on the picker key from one that keys it on the title. That is
    # the tautology `M28` shipped behind. A fixture where the two differ is the only kind
    # that tests anything, so the assertion builds one.
    distinct = dict(m)
    distinct['board'] = dict(m['board'],
                             title='Revenue Feud (Ward Night Edition)',
                             pickerKey='Revenue Feud')
    dp = os.path.join(tmp, 'distinct.map.json')
    open(dp, 'w', encoding='utf-8').write(json.dumps(distinct))
    dgames = os.path.join(tmp, 'distinct-games')
    os.makedirs(dgames, exist_ok=True)
    dm = os.path.join(dgames, 'games.json')
    open(dm, 'w', encoding='utf-8').write(open(manifest_path, encoding='utf-8').read())
    dproc = run(dp, CSV, ('--games-dir', dgames, '--manifest', dm, '--write'))
    dmanifest = load(dm) if dproc.returncode == 0 else {'games': {}}
    filename = m['board']['filename']
    check('the manifest entry is keyed on pickerKey, asserted where it DIFFERS from title',
          dmanifest['games'].get('Revenue Feud') == filename
          and 'Revenue Feud (Ward Night Edition)' not in dmanifest['games'],
          f'manifest keys: {sorted(dmanifest["games"])}')

    manifest = load(manifest_path)
    key = m['board']['pickerKey']
    check('the shipped map\'s board is reachable from the generated manifest',
          manifest['games'].get(key) == filename,
          f'games[{key!r}] = {manifest["games"].get(key)!r}')

    # A key the manifest schema refuses must not be producible from a legal map. The board
    # TITLE is free-form and may carry an em dash or a quote; the picker key is what lands.
    hostile = dict(m)
    hostile['board'] = dict(m['board'], title='Revenue "Feud" — \\ / <script>')
    hp = os.path.join(tmp, 'hostile.map.json')
    open(hp, 'w', encoding='utf-8').write(json.dumps(hostile))
    games = os.path.join(tmp, 'hostile-games')
    os.makedirs(games, exist_ok=True)
    hm = os.path.join(games, 'games.json')
    open(hm, 'w', encoding='utf-8').write(open(manifest_path, encoding='utf-8').read())
    proc = run(hp, CSV, ('--games-dir', games, '--manifest', hm, '--write'))
    ok = proc.returncode == 0 and validate('games', hm).returncode == 0
    check('a board title full of quotes and backslashes still yields a valid manifest',
          ok, proc.stderr.strip()[:300])


def test_generator_refuses_to_write_an_invalid_board(tmp):
    """M32 — the validator gate, asserted THROUGH THE GENERATOR.

    The first version of this assertion drove tools/validate-board.mjs directly and
    checked that it refuses a 16-column board. It does. But that tests the CLI, not the
    tool: M32 deleted the gate from csv-to-board.py outright and the suite stayed green at
    25/25, because nothing here ever asked whether the GENERATOR consults it. So the
    mutation is applied where it lives — a map that produces an over-cap board — and the
    assertion reads the generator's exit code and the absence of the file.
    """
    m = load(MAP)
    m['columns'] = m['columns'] * 2  # 16 columns; the cap is 12
    mp = os.path.join(tmp, 'over.map.json')
    open(mp, 'w', encoding='utf-8').write(json.dumps(m))

    games = os.path.join(tmp, 'over-games')
    os.makedirs(games, exist_ok=True)
    manifest = os.path.join(games, 'games.json')
    open(manifest, 'w', encoding='utf-8').write(
        open(os.path.join(REPO, 'games', 'games.json'), encoding='utf-8').read())
    before = open(manifest, encoding='utf-8').read()

    proc = run(mp, CSV, ('--games-dir', games, '--manifest', manifest, '--write'))
    check('the generator REFUSES to write a board the engine would reject',
          proc.returncode != 0, f'exit was {proc.returncode}')
    check('and it says so in the engine\'s own words, naming the cap',
          '12 columns' in proc.stderr, proc.stderr.strip()[:300])
    check('a refused run leaves no board file behind',
          not os.path.exists(os.path.join(games, 'revenue-feud.json')))
    check('a refused run leaves games.json untouched',
          open(manifest, encoding='utf-8').read() == before)


def test_dry_run_writes_nothing(tmp):
    games = os.path.join(tmp, 'dry')
    os.makedirs(games, exist_ok=True)
    manifest = os.path.join(games, 'games.json')
    open(manifest, 'w', encoding='utf-8').write(
        open(os.path.join(REPO, 'games', 'games.json'), encoding='utf-8').read())
    before = open(manifest, encoding='utf-8').read()
    proc = run(MAP, CSV, ('--games-dir', games, '--manifest', manifest))
    check('a dry run exits 0', proc.returncode == 0, proc.stderr)
    check('a dry run writes no board file',
          not os.path.exists(os.path.join(games, 'revenue-feud.json')))
    check('a dry run leaves games.json byte-identical',
          open(manifest, encoding='utf-8').read() == before)


def test_no_respondent_text_reaches_the_board(board):
    """Rewritten: the original could not fail.

    It asserted `'@' not in json.dumps(board)`. Answer text comes from the map's `label`
    and never from the CSV, and the email column is in `ignoreColumns`, so that was true
    by construction. Review proved it: a mutation putting RAW RESPONDENT TEXT on the board
    (`a['label']` -> `a['from'][0]`) left the PII assertion green.

    So the assertion now names the actual respondent strings — the two email addresses and
    the 90-word rant — and checks none of them appear. Those differ between a board built
    from map labels and one built from raw responses, which is the only property worth
    asserting here.
    """
    if not board:
        return
    text = json.dumps(board, ensure_ascii=False)
    with open(CSV, encoding='utf-8') as fh:
        raw = fh.read()
    leaked = [s for s in raw.replace('"', ',').split(',')
              if '@' in s and '.' in s and len(s) > 8]
    check('no respondent email address reaches the generated board',
          not any(e in text for e in leaked),
          f'leaked one of {leaked}')
    check('and no raw response text reaches it either — labels come from the MAP',
          'fully saturated with evil' not in text and 'the spine' not in text,
          'raw respondent wording is on the board')


def test_manifest_preserves_every_other_board(tmp, manifest_path):
    """The behaviour that would be catastrophic, and that 28/28 did not cover.

    Review's mutation MX1 reduced build_manifest to `{picker_key: filename}` — every other
    board vanishes from the picker — and the suite stayed green, because the assertions
    asked only "is it valid" and "is MY key present". Both are true of the wiping
    implementation. That is the fixture-satisfies-both pattern the register already
    records twice.
    """
    if not manifest_path:
        return
    before = load(os.path.join(REPO, 'games', 'games.json'))['games']
    after = load(manifest_path)['games']
    missing = {k: v for k, v in before.items() if after.get(k) != v}
    check('every board already in games.json survives regeneration, value intact',
          not missing, f'lost or changed: {missing}')
    check('and their ORDER is preserved — order decides which board the picker preselects',
          [k for k in after if k in before] == [k for k in before],
          f'before {list(before)}\nafter  {[k for k in after if k in before]}')


def test_every_board_in_games_dir_is_reachable(tmp):
    """The defect found earlier this session, given an assertion.

    `games/revenue-feud.json` shipped valid, served, and invisible: a static site has no
    directory listing, so a board absent from games.json cannot be reached from the
    picker. The browser suite cannot catch this — it cannot enumerate games/ — which is
    why deleting the entry leaves it green at 450/450. This harness CAN list the
    directory, so the assertion belongs here.
    """
    games_dir = os.path.join(REPO, 'games')
    manifest = load(os.path.join(games_dir, 'games.json'))
    listed = set(manifest['games'].values())
    on_disk = {f for f in os.listdir(games_dir)
               if f.endswith('.json') and f != 'games.json'}
    orphans = sorted(on_disk - listed)
    check('every board file in games/ is reachable from games.json',
          not orphans,
          f'{orphans} are served but absent from the manifest, so no host can open them')
    ghosts = sorted(listed - on_disk)
    check('and games.json names no board that is not there',
          not ghosts, f'{ghosts} are listed but missing from games/')


def test_manifest_has_no_duplicate_keys(tmp):
    """A duplicate picker key is invisible to every gate the project has.

    Found during C20: games.json reached this state with "Revenue Feud" listed twice, and
    BOTH validators called it valid — JSON.parse and json.load each take last-wins
    silently, so by the time the schema sees the object the duplicate is gone. The shape
    is legal; the file is wrong. Only the raw text knows.
    """
    import collections
    seen = {}

    def hook(pairs):
        for k, _ in pairs:
            seen[k] = seen.get(k, 0) + 1
        return dict(pairs)

    with open(os.path.join(REPO, 'games', 'games.json'), encoding='utf-8') as fh:
        json.load(fh, object_pairs_hook=hook)
    dupes = sorted(k for k, n in seen.items() if n > 1)
    check('games.json declares no key twice — last-wins hides this from both validators',
          not dupes, f'duplicated: {dupes}')


def test_a_new_survey_question_is_an_error(tmp):
    """The other half of check_columns. Only the `missing` half had a fixture.

    Review's mutation blanked `unaccounted` and the suite stayed green: a survey that
    GAINS a question — the normal way a Google Form changes — would have been silently
    ignored, which is the same class of silence the unmapped-answer gate exists to break.
    """
    with open(CSV, encoding='utf-8') as fh:
        lines = fh.read().splitlines()
    lines[0] += ',Which ward do you live in?'
    for i in range(1, len(lines)):
        lines[i] += ',49'
    grown = os.path.join(tmp, 'grown.csv')
    open(grown, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    proc = run(MAP, grown)
    check('a NEW CSV column fails the run rather than being silently ignored',
          proc.returncode != 0, f'exit was {proc.returncode}')
    check('and the failure names the new question',
          'Which ward do you live in?' in proc.stderr, proc.stderr.strip()[:200])


def test_zero_count_answer_never_collects_a_point(tmp):
    """The apportion docstring promises this; no fixture exercised it.

    The shipped map has no zero-count answer, so `if counts[i] > 0` could be changed to
    `if True` with the suite green. A map entry nobody voted for is the realistic case —
    it is what a stale map looks like after a question is reworded.
    """
    m = load(MAP)
    m['columns'][0]['answers'].append({'label': 'Nobody At All', 'from': ['Nobody At All']})
    mp = os.path.join(tmp, 'zero.map.json')
    open(mp, 'w', encoding='utf-8').write(json.dumps(m))
    games = os.path.join(tmp, 'zero-games')
    os.makedirs(games, exist_ok=True)
    manifest = os.path.join(games, 'games.json')
    open(manifest, 'w', encoding='utf-8').write(
        open(os.path.join(REPO, 'games', 'games.json'), encoding='utf-8').read())
    proc = run(mp, CSV, ('--games-dir', games, '--manifest', manifest, '--write'))
    if proc.returncode != 0:
        check('a zero-response answer still generates', False, proc.stderr[:200])
        return
    board = load(os.path.join(games, 'revenue-feud.json'))
    cell = next(c for c in board['board']['columns'][0]['cells'] if c['answer'] == 'Nobody At All')
    check('an answer with zero responses is worth zero points, never one spare remainder',
          cell['value'] == 0, f'it came out at {cell["value"]}')
    check('the column still sums to exactly 100 around it',
          sum(c['value'] for c in board['board']['columns'][0]['cells']) == 100)
    check('and the run WARNS that the answer has no responses',
          'no responses' in proc.stdout, proc.stdout.strip()[-200:])


def test_zero_point_answer_is_reported(tmp):
    """The case that only appears once the survey grows — which is the point of the tool.

    At 17 responses every kept answer is worth at least 6. At ~290 a real answer with one
    vote apportions to 0: an unplayable row, permitted by the schema (value min is
    -1000000) and therefore invisible to both validation gates. Nothing but this warning
    stands between that and a board on a projector.
    """
    with open(CSV, encoding='utf-8') as fh:
        rows = fh.read().splitlines()
    header, body = rows[0], rows[1:]
    # One response repeated until a single-vote answer rounds to nothing.
    grown = os.path.join(tmp, 'big.csv')
    open(grown, 'w', encoding='utf-8').write(
        '\n'.join([header] + body + [body[0]] * 280) + '\n')
    proc = run(MAP, grown)
    check('a kept answer that apportions to 0 points is REPORTED, not shipped silently',
          'apportions to 0 points' in proc.stdout,
          proc.stdout.strip()[:400] or proc.stderr.strip()[:200])


def test_board_header_fields_come_from_the_map(tmp, board):
    """Nothing asserted title/theme/animation/gameType at all.

    Review swapped `theme` for `gameType` in the emitted board and the suite stayed green
    — and so did the structural validator, because both are legal strings. Caught now by
    this, and independently by the bundle gate below.
    """
    if not board:
        return
    m = load(MAP)['board']
    for field in ('title', 'gameType', 'theme', 'animation'):
        check(f'the board\'s {field} is the map\'s {field}',
              board.get(field) == m[field],
              f'expected {m[field]!r}, got {board.get(field)!r}')


def test_generator_refuses_a_theme_that_is_not_in_the_manifest(tmp):
    """The gate must be the BUNDLE stage, not the structural one.

    `validateDocument` checks shapes. Whether a theme is in themes/themes.json, and
    whether a gameType names a config that exists, are cross-reference checks that run
    only from `validateBundle`. A board with "theme": "marque" passes every shape rule and
    does not load. The first version of this tool called it valid and wrote it.
    """
    for field, value, word in (('theme', 'marque', 'themes.json'),
                               ('gameType', 'feudd', 'gametypes/')):
        m = load(MAP)
        m['board'] = dict(m['board'], **{field: value})
        mp = os.path.join(tmp, f'bad-{field}.map.json')
        open(mp, 'w', encoding='utf-8').write(json.dumps(m))
        games = os.path.join(tmp, f'bad-{field}-games')
        os.makedirs(games, exist_ok=True)
        manifest = os.path.join(games, 'games.json')
        open(manifest, 'w', encoding='utf-8').write(
            open(os.path.join(REPO, 'games', 'games.json'), encoding='utf-8').read())
        proc = run(mp, CSV, ('--games-dir', games, '--manifest', manifest, '--write'))
        check(f'a board whose {field} does not resolve is REFUSED, not written',
              proc.returncode != 0 and not os.path.exists(
                  os.path.join(games, 'revenue-feud.json')),
              f'exit {proc.returncode}')
        check(f'and the refusal points at {word}',
              word in proc.stderr, proc.stderr.strip()[:250])


def test_filename_cannot_escape_the_games_directory(tmp):
    """`filename` is used as a WRITE path. CLAUDE.md gives ?game= a no-traversal rule.

    Review demonstrated a map writing outside the repo AND outside the temp directory,
    before validation, with no cleanup — os.path.join discards everything left of an
    absolute path.
    """
    victim = os.path.join(tmp, 'victim.json')
    open(victim, 'w', encoding='utf-8').write('PRECIOUS')
    for bad in ('../../escaped.json', victim, 'games/x.json', 'notes.txt', '.hidden.json'):
        m = load(MAP)
        m['board'] = dict(m['board'], filename=bad)
        mp = os.path.join(tmp, 'escape.map.json')
        open(mp, 'w', encoding='utf-8').write(json.dumps(m))
        proc = run(mp)
        check(f'filename {bad!r} is refused', proc.returncode != 0, proc.stdout[:200])
    check('and the file it aimed at is untouched',
          open(victim, encoding='utf-8').read() == 'PRECIOUS')


def test_both_files_land_or_neither(tmp):
    """A board written without its manifest line IS the defect this tool prevents.

    The first version wrote the board first, outside the try block: a failing manifest
    write left a valid, served, unreachable board behind and printed a traceback.
    """
    games = os.path.join(tmp, 'atomic')
    os.makedirs(games, exist_ok=True)

    # The manifest must READ fine and fail to WRITE, or the run never reaches the write
    # phase and the mutation is untestable. The first version of this assertion made the
    # manifest path a directory — which fails in build_manifest, before any file is
    # written, so removing the rollback left it green. A real manifest in a read-only
    # DIRECTORY is the fixture that separates the two: os.replace needs write permission
    # on the directory, not on the file.
    locked = os.path.join(tmp, 'locked')
    os.makedirs(locked, exist_ok=True)
    manifest = os.path.join(locked, 'games.json')
    with open(os.path.join(REPO, 'games', 'games.json'), encoding='utf-8') as fh:
        open(manifest, 'w', encoding='utf-8').write(fh.read())
    os.chmod(locked, 0o555)
    try:
        proc = run(MAP, CSV, ('--games-dir', games, '--manifest', manifest, '--write'))
    finally:
        os.chmod(locked, 0o755)

    check('a failing manifest write fails the run', proc.returncode != 0,
          f'exit was {proc.returncode}')
    check('and leaves NO board file behind — not a valid, unreachable one',
          not os.path.exists(os.path.join(games, 'revenue-feud.json')),
          'the board landed without its manifest entry: the exact defect C20 prevents')
    check('and leaves no .tmp debris',
          not [f for f in os.listdir(games) if f.endswith('.tmp')],
          f'debris: {os.listdir(games)}')
    check('and reports it without a traceback',
          'Traceback' not in proc.stderr, proc.stderr.strip()[:200])


def test_a_long_response_fails_clearly(tmp):
    """Survey text is effectively untrusted: one real response runs to 90 words.

    It reaches the board only if a map author makes it a label, which is the realistic
    mistake. What must not happen is a confusing failure.
    """
    m = load(MAP)
    m['columns'][0]['answers'][0] = {'label': 'x' * 5000, 'from': ['Elon Musk']}
    mp = os.path.join(tmp, 'long.map.json')
    open(mp, 'w', encoding='utf-8').write(json.dumps(m))
    proc = run(mp)
    check('an over-length answer label is refused', proc.returncode != 0,
          f'exit was {proc.returncode}')
    check('and the refusal names the limit rather than dumping 5000 characters',
          'characters' in proc.stderr and len(proc.stderr) < 4000,
          f'stderr was {len(proc.stderr)} bytes')


def main():
    print('C20 — csv-to-board')
    with tempfile.TemporaryDirectory() as tmp:
        board, manifest_path = test_happy_path(tmp)
        test_columns_total_100(board)
        test_apportionment_basis(board)
        test_dropped_answers_do_not_reach_the_board(board)
        test_unmapped_answer_is_an_error(tmp)
        test_renamed_csv_column_is_an_error(tmp)
        test_manifest_entry_is_a_valid_manifest(tmp, manifest_path)
        test_generator_refuses_to_write_an_invalid_board(tmp)
        test_dry_run_writes_nothing(tmp)
        test_no_respondent_text_reaches_the_board(board)
        test_manifest_preserves_every_other_board(tmp, manifest_path)
        test_every_board_in_games_dir_is_reachable(tmp)
        test_manifest_has_no_duplicate_keys(tmp)
        test_a_new_survey_question_is_an_error(tmp)
        test_zero_count_answer_never_collects_a_point(tmp)
        test_zero_point_answer_is_reported(tmp)
        test_board_header_fields_come_from_the_map(tmp, board)
        test_generator_refuses_a_theme_that_is_not_in_the_manifest(tmp)
        test_filename_cannot_escape_the_games_directory(tmp)
        test_both_files_land_or_neither(tmp)
        test_a_long_response_fails_clearly(tmp)

    total = len(PASSED) + len(FAILED)
    print(f'\n{len(PASSED)}/{total} assertions passed')
    return 1 if FAILED else 0


if __name__ == '__main__':
    sys.exit(main())
